---
services:
  gateway:
    image: bwdesigngroup/ignition-docker:8.1.36
    hostname: danone-udt
    volumes:
      - ./ignition-data:/workdir
      - ./backups/gateway.gwbk:/restore.gwbk
    environment:
      SYMLINK_GITIGNORE: false
      SYMLINK_LOGBACK: false
      GATEWAY_SYSTEM_NAME: danone-udt
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: danone-udt.localtest.me
    labels:
      traefik.enable: "true"
      traefik.hostname: "danone-udt"
    command: >
      -r /restore.gwbk
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
